import './globals.css'

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
import Nav from '@/modules/layout/Nav'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props) {
  return (
    <html lang="en">
      <body className={inter.className}>{props.children}</body>
    </html>
  )
}
